### ISSUE TITLE
I installed it but...

### ISSUE THREAD

**Issue by DesigningKnights** [jinyafeng/DocumentationAssistant#1]
How do I use it?  You provided no documentation. 

Do I use a key stroke?  Or is there another way?  I'd like to add documentation to existing code.

**Comment by jinyafeng** [comment]
I have added some instructions on ReadMe file. Please let me know whether it is helpful to you or you have any other questions.

**Comment by DesigningKnights** [comment]
Ok that helped. Thank you!
I did eventually figure it out, but it was kind of a fluke that I did.  The instructions will help others not have to guess how to use it.

**Comment by jinyafeng** [comment]
Great, thank you remind it to me. It is a thing that I should do early. Hope the tool can help you!
