### ISSUE TITLE
Can you support selecting a file and automatically adding XML comments to all class public and other attribute methods in this file

### ISSUE THREAD

**Issue by worldofchu** [jinyafeng/DocumentationAssistant#11]
Can you support selecting a file and automatically adding XML comments to all class public and other attribute methods in this file
it like ghostdoc

**Comment by jinyafeng** [comment]
I tried to implement the feature before but not let it worked.
But I will try to support it when I have time.

**Comment by jinyafeng** [comment]
Sorry, I don't have times to maintain this and I'm going to archive the repository. Thanks!
