### ISSUE TITLE
Documenting a top-level entity add extra line break.

### ISSUE THREAD

**Issue by sloscialo** [jinyafeng/DocumentationAssistant#13]
When using the context menu to add documentation to a top-level entity such as a class or interface, the initial template adds an additional line break between the closing `</summary>` tag and the code. For example,

``` C#
/// <summary>
/// The project service.
/// </summary>

public class ProjectService : IProjectService
...
```

Seen in Visual Studio 2022 Preview and Visual Studio 2022.
DocumentationAssistant v. 1.7.0

**Comment by jinyafeng** [comment]
Tested and found the issue will shown only when using c#10 with file scoped namespace? Am I right?

**Comment by sloscialo** [comment]
Yes, you are correct. Didn't even think about the file-scoped namespace as an issue (or C# 10 for that matter).

**Comment by jinyafeng** [comment]
I did some research and thought my generation is good，looks like it is added by visual studio automatically. I will not fix it as it is a special issue in file scope class with low impact(you can easily remove it.) Thanks for the issue.
