### ISSUE TITLE
Various minor issues with VS2022

### ISSUE THREAD

**Issue by oleg-shilo** [jinyafeng/DocumentationAssistant#14]
It's great to see the extension of this sort. Really glad GhostDoc is no longer the only option. Love it 

----

After going through the list of issues I have noticed that a few issues are poping up again and again and it seems like your users really want to get the desired functionality:
- Allow conditionally exclude non-public members. It is the same as #6 and it is still not fixed even though the issue is closed:
  As you can see below the right extension is still generating warnings:
  ![image](https://user-images.githubusercontent.com/16729806/147729279-e8263b1d-8e7c-4c3e-952b-6bf58ec6d9ff.png)
  ![image](https://user-images.githubusercontent.com/16729806/147729140-76c66b30-2bd7-495a-8701-739bc4de8461.png)
 I suggest that instead of creating two extensions with slightly different functionality you simply allow your users to choose to enable/disable the functionality they want. You will never have them agree so let them choose instead 😄 
 The configuration page seems to exist judging from the #8 thread. But at least on V2022, the options dialog does not have it available.
 - Another enhancement that was asked a few times is the hotkey binding for the "Fixing missing documentation header" (#5).
 As it was mentioned one can use `Ctrl+.` or `Alt+Enter`. Though this is not an adequate equivalent as it simply triggers the context menu. And then it requires menu navigation and the selection of the fix scope. 
 Though the users are asking for a simple single-step action (for the signature at the cursor) identical to `Ctrl+Shift+D` so familiar in GostDoc.
 If you just expose the command used can bind it by itself.

**Comment by jinyafeng** [comment]
I can get you are very love this, I appreciate it. Thanks.

For your screenshot issue,I do a quick test and it has no issue in VS2022 Community. Please let me know what is your VS edition
![image](https://user-images.githubusercontent.com/9289938/147810913-5d8c2741-aa4e-4a74-b611-a3fcff000d52.png)

For feature: provide a option page to enable/disable non-public members to be documented, I have implemented a version but it is not working. So I removed it later.

For feature: Applying the fix by using a keystroke. This should be a good feature But I don't have too much time to research and implement. I hope you can forgive me, But I can reopen that issue and write in VS market, hope anyone can help implement this.

**Comment by jinyafeng** [comment]
I can get you are very love this, I appreciate it. Thanks.

For your screenshot issue,I do a quick test and it has no issue in VS2022 Community. Please let me know what is your VS edition
![image](https://user-images.githubusercontent.com/9289938/147810913-5d8c2741-aa4e-4a74-b611-a3fcff000d52.png)

For feature: provide a option page to enable/disable non-public members to be documented, I have implemented a version but it is not working. So I removed it later.

For feature: Applying the fix by using a keystroke. This should be a good feature But I don't have too much time to research and implement. I hope you can forgive me, But I can reopen that issue and write in VS market, hope anyone can help implement this.

**Comment by oleg-shilo** [comment]
I am using VS2022 "Professional"

**Comment by jinyafeng** [comment]
![image](https://user-images.githubusercontent.com/9289938/148024079-654e9469-2cfc-4d65-a091-315f3b4be63f.png)

VS 2022 Pro is working for me also.  Please try to uninstall it and then re-install and don't install DocumentationAssistant  and DocumentationAssistantPublicMembersOnly both.

**Comment by oleg-shilo** [comment]
Well, I doubt it has something to do with the VS version. :(

![image](https://user-images.githubusercontent.com/16729806/148063366-6af50d08-e35d-4a73-b41f-425950ffb3b4.png)

![image](https://user-images.githubusercontent.com/16729806/148063417-6cda0c92-eda9-42b6-9bea-a3efd6e7df95.png)

It's a difficult task for you now to support two different extensions and try to troubleshoot them effectively. That's why I suggested you consider having only one extension but allow customization.

Anyway, good luck with your project.

**Comment by oleg-shilo** [comment]
Found the problem. Both 'DocumentationAssistant' and 'DocumentationAssistantPublicMem...' were installed.
While it was a user (my) mistake, you probably see now why it is not a good idea to allow two conflicting distributions of the same product to be publically available at the same time without any restrictions.

**Comment by jinyafeng** [comment]
It is not a good way really. I will add an attention to the extension's instruction, thanks.

**Comment by jinyafeng** [comment]
Sorry, I don't have times to maintain this and I'm going to archive the repository. Thanks!
