### ISSUE TITLE
Invalid cref on generic class constructor.

### ISSUE THREAD

**Issue by mcaden** [jinyafeng/DocumentationAssistant#15]
Generics should include their typeparams in the cref of the constructor.

Actual (invalid):

    public class MyGeneric<T, K>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MyGeneric"/> class.
        /// </summary>
        public MyGeneric() {}
    }

Expected:

    public class MyGeneric<T, K>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MyGeneric{T, K}"/> class.
        /// </summary>
        public MyGeneric() {}
    }

Note that because these are XML comments the comments use curly-brackets instead of angle-brackets.

**Comment by jinyafeng** [comment]
Sorry, I don't have times to maintain this and I'm going to archive the repository. Thanks!
