### ISSUE TITLE
Update documentation on add/delete params

### ISSUE THREAD

**Issue by NeoKabamaru** [jinyafeng/DocumentationAssistant#16]
Hello,

This is not an error, but a request:

Would it be possible (if not already) to update the documentation when parameters are added or removed?

It's not a lot of work to do, but if you do batch adding or removing parameters, it would save a lot of time.

Thank you very much and greetings.

**Comment by jinyafeng** [comment]
Sorry, I don't have times to maintain this and I'm going to archive the repository. Thanks!
