### ISSUE TITLE
Suggesting missing documentation of method in .aspx file

### ISSUE THREAD

**Issue by Hefaistos68** [jinyafeng/DocumentationAssistant#17]
For some reason the extension is marking code in aspx files for documentation, happens also for built-in methods of asp controls.
![image](https://user-images.githubusercontent.com/8855055/168280722-6859befd-4e3b-422a-b09d-472a09b2f333.png)

As you can see here, not all methods are marked, even when they are the same:
![image](https://user-images.githubusercontent.com/8855055/168281234-7283a532-5b0d-4b23-8960-c53f8bab1ef6.png)
The first DataBinder.Eval isnt, the second is.

**Comment by jinyafeng** [comment]
Sorry, I don't have times to maintain this and I'm going to archive the repository. Thanks!
