### ISSUE TITLE
How to handle partial classes?

### ISSUE THREAD

**Issue by kgraefe** [jinyafeng/DocumentationAssistant#2]
I have a class that is distributed over multiple files using the "partial class" statement. I added a summary to class in the main file. In the other files the class name still gets underlined and a warning is generated the a documentation header is required.

I am new to C# so I don't know what the convention is here, but I don't want to maintain the same summary text on multiple files. How would I handle that situation?

**Comment by jinyafeng** [comment]
Yes, multiple partial files shouldn't have same summary text because they have different role although they have same class name.

You'd better generate basic summary text and then add specific text to describe what's role it represented.

**Comment by kgraefe** [comment]
I solved it by disabling the warning for classes in files with two dots in their name using an `.editorconfig` in the solution:
```
# Disable ClassDocumentationHeader warning for all files with two dots in their
# name, e.g. "MainWindow.Designer.cs" or "Native.Crypto.cs".
# The convention here is that those are partial classes with a corresponding
# main file which ships an appropriate documentation.
[*.*.cs]
dotnet_diagnostic.ClassDocumentationHeader.severity = none
```

Thank you for the DocumentationAssistant extension. It is really helpful to me.
