### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by AroglDarthu** [jinyafeng/DocumentationAssistant#3]
I came across your extension because Ghost Doc is getting a bit too bloated for my liking.
The following additions would really make your extension more useful for me:
- Applying the fix by using a keystroke. A nice default would be: CTRL-SHIFT-D
- Excluding non-public members by default. We only tend to document our public API. Would be really nice to have a way to configure when to display the warning.

**Comment by jinyafeng** [comment]
Thanks for your good suggestions.

For keystroke issue, it is already available for us. The fix option is integration in VS quick actions. You can use shortcut (Alter + Enter or Ctrl + .) to quickly add.

For Excluding non-public members by default. It is good idea. I will research it to provide a way to configure it.

**Comment by jinyafeng** [comment]
Hi Friend, For this feature "Excluding non-public members by default. " I had implemented it by adding a new version. Please download it from here [VsMarketplace](https://marketplace.visualstudio.com/items?itemName=jinyafeng.DocumentationAssistantPublicMembersOnly). **If you already installed previous product, please uninstall it firstly.**

I want to make a configuration from tools > option settings. But I encountered a problem that don't know how to read the setting from different project.

Thanks for your great advice. I appreciate it.

**Comment by oansquer** [comment]
Hi,

DocumentationAssistantPublicMembersOnlyPreview seems to work fine but show me warnings for public members on private classes. Is it possible to do something?
Thanks for your work on this extension.

**Comment by jinyafeng** [comment]
The extension will consider it as a public member so the warnings shown. It is a bug I will fix it. Thanks！

**Comment by jinyafeng** [comment]
This is a good suggestion- Applying the fix by using a keystroke. A nice default would be: CTRL-SHIFT-D
VS quick action is not convenient enough. 

Thanks for the suggestion. I created a new issue #5 to track it.

**Comment by jinyafeng** [comment]
The configuration feature have been supported at latest version. Thanks for your good suggestion.
