### ISSUE TITLE
Support for VS 2019 v16.4 inheritdoc comments

### ISSUE THREAD

**Issue by WizX20** [jinyafeng/DocumentationAssistant#4]
**Add support for `<inheritdoc/>` comments**

This (much wanted) feature was added with visual studio 2019 16.4:
https://developercommunity.visualstudio.com/idea/412325/add-intellisense-support-for-the-tag-in-xml-docume.html

Official Microsoft Docs:
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/inheritdoc

_Do not throw warnings/errors when the inheritdoc tag is used:_

![image](https://user-images.githubusercontent.com/1008647/82049780-3d4f2500-96b7-11ea-8243-51bd74918ebe.png)

**Comment by jinyafeng** [comment]
It is good feature. I had supported it. Thanks.
