### ISSUE TITLE
Public members in private class should not show warnings.

### ISSUE THREAD

**Issue by jinyafeng** [jinyafeng/DocumentationAssistant#6]
Hi,

DocumentationAssistantPublicMembersOnlyPreview seems to work fine but show me warnings for public members on private classes. Is it possible to do something?
Thanks for your work on this extension.

_Originally posted by @oansquer in https://github.com/jinyafeng/DocumentationAssistant/issue_comments/693643966_

**Comment by michaelswells** [comment]
I believe that a public object even within a private class should have a summary. As a developer, I might want to call that object and want to know what it is/does. :) Granted, maybe there should be a setting to disable checking private classes.

**Comment by oansquer** [comment]
You can only call a private class public member from the outer class.
If you really want to comment those members, you should not use DocumentationAssistantPublicMembersOnlyPreview and should use DocumentationAssistant no?

**Comment by jinyafeng** [comment]
> I believe that a public object even within a private class should have a summary. As a developer, I might want to call that object and want to know what it is/does. :) Granted, maybe there should be a setting to disable checking private classes.

I think it should be an issue because its client is only its parent class. 
But this doesn't mean I am right. You can also add summary for it manually.  :)

If you want to document all members(public + private ), you can use the DocumentationAssistant verision.
If you want to document only public members, you can use the DocumentationAssistantPublicMembersOnly version.
For configuration/setting, I will probably support it in future.

**Comment by jinyafeng** [comment]
The issue have been fixed at latest version "DocumentationAssistant".

The "DocumentationAssistantPublicMembersOnlyPreview" version have been removed since "DocumentationAssistant" have supported configuration to disable checking private members.

Thanks
