### ISSUE TITLE
Private member option in last version

### ISSUE THREAD

**Issue by oansquer** [jinyafeng/DocumentationAssistant#8]
Hello,

I checked the new option:

![image](https://user-images.githubusercontent.com/3694381/102082696-ad22bb00-3e12-11eb-8165-2da3ef01e329.png)

I restarted Visual Studio 2019 but I have warnings on private members:

![image](https://user-images.githubusercontent.com/3694381/102082564-76e53b80-3e12-11eb-8d82-ee2539a3086e.png)

Is this a bug?

Thank you.

Olivier Ansquer

**Comment by jinyafeng** [comment]
I tested this in my Visual Studio 2017 Community/Professional and Visual Studio 2019 Community. All of them are worked.
![image](https://user-images.githubusercontent.com/9289938/102215370-95336000-3f14-11eb-98b6-b39808034198.png)

Please let me know whether the issue will be also reproduced at private class/constructor/property/method

Also let me know what version of VS you used.

**Comment by oansquer** [comment]
I have VS 2019 pro:

![image](https://user-images.githubusercontent.com/3694381/102216754-e7a45a80-3edb-11eb-9048-fe6d0d642b37.png)

I reproduce the problem on a new project:

![image](https://user-images.githubusercontent.com/3694381/102216716-d9eed500-3edb-11eb-9d2c-0c97ef0a35fe.png)

It is as if the option was not taken into account.

**Comment by jinyafeng** [comment]
Okay, I will download a VS 2019 pro to see what will happen.

**Comment by jinyafeng** [comment]
It will really not be worked in VS 2019 Pro. I will fix it. 
If you think warning line is not good, please use DocumentationAssistantPublicMembersOnly temporarily.
Thanks a lot you can report the bug.

**Comment by jinyafeng** [comment]
I updated my VS 2019 Community from 16.5.4 to 16.8.3. It doesn't work also. 
It does can work at VS 2019 Community 16.5.4. The issue seems to relate to Visual Studio 2019 itself.

**Comment by jinyafeng** [comment]
Remove the option function because it is not working. you can still use the DocumentationAssistantPublicMembersOnly extension. I have updated it to VS2022. Thanks.
