### ISSUE TITLE
Support a button to generate comments for all members.

### ISSUE THREAD

**Issue by jinyafeng** [jinyafeng/DocumentationAssistant#9]
Support a button to generate comments for all members.

The idea is from one user's question https://marketplace.visualstudio.com/items?itemName=jinyafeng.DocumentationAssistant&ssr=false#qna.

**Comment by Hefaistos68** [comment]
This actually works already fine through the IntelliCode actions.  One can select to fix this one occurrence, by document, project or solution.

**Comment by jinyafeng** [comment]
Yes, your said is really what I want to do.

**Comment by jinyafeng** [comment]
Don't find a good way to do this and don't have too much time now. Close it temporarily.
